export const blogs = [
    {
      id: 1,
      title: "How we placed over 500 people at a leading AI unicorn.",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-10-01",
      author: "Dr. John Doe",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e2902673d",
      role: "Co-founder / CEO",
      image: "/path/to/image.jpg"
    },
    {
      id: 2,
      title: "How Machine Learning is Revolutionizing Healthcare",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-09-15",
      author: "Dr. John Doe",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e2902670d",
      role: "Healthcare Specialist",
      image: "https://i.ibb.co.com/j37SsqN/1-c-G6-U1qst-YDijh9b-PL42e-Q.jpg"
    },
    {
      id: 3,
      title: "Top 10 Trends in Web Development for 2024",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-08-30",
      author: "Jane Smith",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026705d",
      role: "Web Developer",
      image: "/path/to/image3.jpg"
    },
    {
      id: 4,
      title: "How to Build Scalable APIs with GraphQL",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-09-05",
      author: "Mike Johnson",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026707d",
      role: "Software Engineer",
      image: "/path/to/image4.jpg"
    },
    {
      id: 5,
      title: "Exploring the Future of Quantum Computing",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-07-18",
      author: "Emily Clark",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e2902672d",
      role: "Quantum Computing Researcher",
      image: "/path/to/image5.jpg"
    },
    {
      id: 6,
      title: "AI in Retail: Enhancing Customer Experience",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-06-21",
      author: "Sarah Lee",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026709d",
      role: "Retail Analyst",
      image: "/path/to/image6.jpg"
    },
    {
      id: 7,
      title: "A Guide to Remote Work in 2024: Tools and Best Practices",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-05-25",
      author: "David Williams",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e290267034d",
      role: "Remote Work Consultant",
      image: "/path/to/image7.jpg"
    },
    {
      id: 8,
      title: "The Role of Cybersecurity in the Age of Digital Transformation",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-04-12",
      author: "Rachel Adams",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29056704d",
      role: "Cybersecurity Expert",
      image: "/path/to/image8.jpg"
    },
    {
      id: 9,
      title: "Data-Driven Marketing: How to Harness the Power of Analytics",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-03-10",
      author: "Alex Green",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e2954264704d",
      role: "Marketing Strategist",
      image: "/path/to/image9.jpg"
    },
    {
      id: 10,
      title: "Sustainable Tech: How Companies Are Reducing Their Carbon Footprint",
      description: "Our team efficiently sourced and vetted over 500 engineers In February, we received a request from a leading AI unicorn for 500 software engineers of varying experience levels to work with researchers and help tutor AI models. The mandate was clear: place as many qualified engineers as quickly as possible. Our team immediately got to work building a custom vetting pipeline drawing from the Mercor talent pool. First, we performed a deep semantic search over AI interviews, resumes, and GitHubs to identify candidates most relevant to the role. We shortlisted talent that had specific experience with the frameworks and languages that the client had requested. Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things Our pool included engineers from around the world – from India to Argentina to Poland – that were ordered by how well their skillset aligned with the role.Second, our team looked at the exact work that the client expected the engineers to do and designed a custom ranking algorithm that predicted which candidates would perform well on the job. We identified which features could correlate the most with success, which included anything from competitive programming experience on their resume to how confident someone sounded during their AI interview. Third, we built out the recruiting infrastructure to confirm the availability and willingness of thousands of people and provide support to them at every stage of the hiring process. We assembled these components in one day and sent an initial batch of 100 candidates to the clients. The results were promising! In the final interview administered by the client, we achieved over an 80% pass rate and outperformed every other vendor they had worked with. However, ambition drove our team further. Our goal was to build the most predictive vetting possible. We did two things",
      date: "2024-02-14",
      author: "Laura Martin",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e54026704d",
      role: "Sustainability Analyst",
      image: "/path/to/image10.jpg"
    }
  ];
  